import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { images } from "@/assets/redesign";
import { SectionHeading } from "@/components/site/SiteLayout";

const problems = [
  ["Ingatlan jogi státusza", "Egy ingatlan lehet önálló ingatlan, telek, ház, ipari létesítmény vagy társasházi lakás. Mind másfajta jogi megközelítést igényel. A státusz felmérése elengedhetetlen a vásárlás előtt."],
  ["Műszaki állapot", "Az ingatlan általános műszaki állapota és a beépített anyagok, rendszerek élettartama."],
  ["Szerkezeti állapot", "Falak, födémek, statika, repedések, utólagos átalakítások nyoma."],
  ["Gépészet és műszaki rendszerek", "Fűtés, víz, szellőzés, elektromos hálózat: állapot, kapacitás, cserekötelezettség."],
  ["Tervrajzok és műszaki dokumentáció", "Ami a papíron van, és ami a valóságban: a kettő közti eltérés a kockázat."],
  ["Látható és rejtett hibák", "Amit friss festés vagy burkolat fed el, és amire érdemes külön figyelni."],
  ["Környezeti és használhatósági szempontok", "Tájolás, zaj, közös részek, megközelítés."],
  ["Felújítási és fenntartási költségek", "Átalakíthatóság, mi kerül pénzbe most, mi két éven belül, és mi lehet visszatérő költség."],
  ["Értékesítési szempontok vizsgálata", "Továbbértékesítésre szánt ingatlannál mekkora beruházást célszerű ráfordítani, hogy utána is versenyképes maradjon a piacon."],
];

const steps = [
 {rail:"Első megtekintés", kicker:"Első lépés", title:"Nézzük meg együtt az ingatlant.", body:"Segítünk akár már az első megtekintés során, még mielőtt bármi konkretizálódna benned az ingatlannal kapcsolatban.", label:"Amivel támogatunk", list:["a neked tetsző hirdetésekből segítünk szűkíteni azokra, amelyeket érdemes megtekinteni","a megtekintés során az ingatlanra vonatkozó szakmai kérdésekkel támogatunk","tudjuk, milyen dokumentumokra van szükség a szerződés aláírása előtt","segítünk eldönteni, érdemes-e egyáltalán továbblépni"],note:"Több ingatlan megtekintése esetén egyedi ajánlatot adunk.",price:"Első megtekintés · Lakás 50 000 Ft‑tól / Ház 70 000 Ft‑tól"},
 {rail:"Helyszíni felmérés", kicker:"Ha továbbléptünk", title:"Együtt nézzük meg a helyszínen.", body:"Ideálisan ekkorra már rendelkezésünkre áll az ingatlan dokumentációja, tervrajzai, a kapcsolódó műszaki anyagok és a jogi dokumentumok. A helyszínen ezeket összevetjük a valós állapottal.",label:"Amit a felmérésen teszünk",list:["műszaki és szerkezeti állapotvizsgálat","gépészeti rendszerek áttekintése","dokumentáció és valóság összevetése","figyelemfelhívás az esetleges hibalehetőségekre"],note:"Amit látunk, dokumentáljuk. Amit nem látunk, annak utánanézünk.",price:"Helyszíni felmérés · Lakás 150 000 Ft‑tól / Ház 200 000 Ft‑tól"},
 {rail:"Szakmai értékelés",kicker:"Tervezőasztal",title:"Leülünk a tervezőasztalhoz, és végigbeszéljük.",body:"A helyszíni tapasztalatokat és a dokumentációt együtt értékeljük, nyugodtan, az ingatlanon kívül.",label:"Amit végigveszünk",list:["mi a probléma","mekkora a kockázat","milyen megoldások vannak","milyen költségekkel számolj","mit érdemes most megtenni","milyen döntési lehetőségeid vannak"],note:"Segítünk átlátni, mit jelent mindez a te döntésed szempontjából.",price:"Szakmai értékelés és tervezés · Lakás 350 000 Ft‑tól / Ház 550 000 Ft‑tól"},
 {rail:"Tervezés",kicker:"Ha megveszed",title:"Megtervezzük, hogyan tovább.",body:"Ha az ingatlan megfelel az elképzeléseidnek, meghatározzuk a szükséges munkákat és prioritásokat, felmérjük a várható költségeket, és összeállítjuk a felújítás menetét.",label:"Amit összeállítunk",list:["szükséges munkák és prioritások","várható költségek reális sávokkal","műszaki megoldási javaslatok","a felújítás menete és ütemezése"],note:"Ha nem veszed meg, segítünk a keretedhez és az igényeidhez megfelelő ingatlant keresni.",price:"Szakmai értékelés és tervezés · Lakás 350 000 Ft‑tól / Ház 550 000 Ft‑tól"},
 {rail:"Megvalósítás",kicker:"Kivitelezés",title:"A tervekből megvalósítás lesz.",body:"Segítünk megfelelő kivitelezőt találni a teljes munkára vagy akár egyes szakágakra. A kivitelezés során koordináljuk a szakágakat, szükség esetén műszaki ellenőrzéssel támogatjuk a munkát, és végigkísérjük a folyamatot az átadásig.",label:"Amit kézben tartunk",list:["kivitelező kiválasztása teljes munkára vagy szakáganként","tervezés","kivitelezés","koordináció","műszaki ellenőrzés","átadás"],note:"Te pedig végig tudod, mi történik, miért történik, és mibe kerül.",price:"Projektmenedzsment · Lakás 1 200 000 Ft‑tól / Ház egyedi ajánlat"},
 {rail:"Az eredmény",kicker:"Döntési pozíció",title:"Egy saját ingatlan, amivel már tudod, mit lehet kezdeni.",body:"Legyen szó saját otthonról, befektetésről vagy későbbi értékesítésről, a cél, hogy az ingatlanban rejlő lehetőségeket és korlátokat ismerve hozd meg a döntéseidet.",label:"Ahol ez számít",list:["saját otthon","befektetés és hozam","későbbi értékesítés","bérbeadás"],note:"Ha a későbbi értékesítés a cél, abban is segítünk, hogy a beruházásod célirányos legyen, felmérve a későbbi értékesítési lehetőségeket és a piacot. Természetesen az értékesítés folyamatában is tudunk segíteni."}
];

const servicePanels = [
 {tab:"Vevői oldal",title:"Mielőtt megveszed.",cta:"Vásárlás előtt →",items:["Vásárlás előtti műszaki felmérés","Ingatlankockázat-felmérés","Dokumentáció és tervrajzok áttekintése","Várható felújítási költségek felmérése","Befektetési célú ingatlan szakmai értékelése","Döntéstámogatás"]},
 {tab:"Eladói oldal",title:"Mielőtt piacra lépsz.",cta:"Eladás előtt →",items:["Eladás előtti műszaki állapotfelmérés","Problémák és kockázatok feltárása","Felújítási és értéknövelési javaslatok","Felújítás koordinációja","Értékesítés előtti felkészítés","Értékesítési támogatás"]},
 {tab:"Bérlői oldal",title:"Mielőtt aláírod.",cta:"Bérlés előtt →",items:["Bérlés előtti állapotfelmérés","Műszaki problémák feltárása","Használhatósági szempontok vizsgálata","Dokumentáció áttekintése","Döntéstámogatás"]}
];

export default function Home() {
 const [problem,setProblem]=useState(0); const [step,setStep]=useState(0); const [manualStep,setManualStep]=useState(false); const [service,setService]=useState(0); const [slide,setSlide]=useState(0); const [manualSlide,setManualSlide]=useState(false);
 useEffect(()=>{if(manualStep)return;const id=window.setInterval(()=>setStep(v=>(v+1)%steps.length),6400);return()=>clearInterval(id)},[manualStep]);
 useEffect(()=>{if(manualSlide)return;const id=window.setInterval(()=>setSlide(v=>(v+1)%images.beforeAfter.length),5200);return()=>clearInterval(id)},[manualSlide]);
 const chooseStep=(i:number)=>{setStep(i);setManualStep(true)}; const moveSlide=(n:number)=>{setSlide((slide+n+4)%4);setManualSlide(true)};
 return <>
  <section className="hero" style={{backgroundImage:`linear-gradient(90deg, color-mix(in oklab, var(--background) 88%, transparent) 0%, color-mix(in oklab, var(--background) 70%, transparent) 48%, color-mix(in oklab, var(--background) 12%, transparent) 100%), url(${images.hero})`}}><div className="site-container hero-content"><p className="hero-kicker">ingatlankockázat.hu</p><h1>Egy ingatlan lehet gyönyörű, és tűnhet jó befektetésnek. Azonban az első benyomás után érhetnek meglepetések.</h1><p className="hero-lead">Szembejöhetnek olyan problémák, amiket elsőre nem veszel észre.</p><Link to="/kapcsolat" className="button-primary">Felülvizsgáltatom az ingatlant →</Link></div></section>
  <section className="section"><div className="site-container narrow reveal"><p className="display-kicker">Mielőtt döntesz</p><p className="lead max-w-4xl">Nézzük meg, milyen állapotban van valójában, milyen kockázatokkal és költségekkel számolj, és milyen lehetőségek vannak benne.</p><p className="body-large">Független műszaki és szakmai támogatás vásárlás, felújítás és értékesítés előtt, közben és után.</p><div className="pill-row">{["Vásárlás","Felújítás","Értékesítés","Bérlés"].map(x=><span className="outline-pill" key={x}>{x}</span>)}</div></div></section>
  <section className="section surface"><div className="site-container problem-grid"><div><SectionHeading kicker="01 A probléma" title="Amit elsőre látsz, az nem feltétlenül a teljes kép."/><p className="body-large reveal">A laikus szem sokszor nem veszi észre egy ingatlan valódi kockázatait. Lehetnek műszaki és jogi problémák, amelyek azonnal vagy csak később okoznak komoly költséget. És lehetnek olyanok is, amelyekről azt sem tudod, hogy meg kellene vizsgálnod.</p><p className="kicker mt-12 reveal">Mi segítünk feltárni</p></div><div className="accordion reveal">{problems.map((p,i)=><div className={`accordion-item ${problem===i?"active":""}`} key={p[0]}><button onClick={()=>setProblem(problem===i?-1:i)} aria-expanded={problem===i}><span>{String(i+1).padStart(2,"0")} · {p[0]}</span><b>{problem===i?"−":"+"}</b></button>{problem===i&&<p>{p[1]}</p>}</div>)}</div></div><p className="site-container closing-line reveal">A cél, hogy az összes fontos kérdésre még a döntés előtt megfelelő válasz legyen.</p></section>
  <section className="quote-section" style={{backgroundImage:`linear-gradient(90deg, color-mix(in oklab, var(--deep) 88%, transparent), color-mix(in oklab, var(--deep) 35%, transparent)),url(${images.quote})`}}><div className="site-container quote-content reveal"><span className="quote-mark">„</span><blockquote>A mai magyar ingatlanpiacon egy laikus első nekifutásra kevesebb információval rendelkezik, mint egy használt autó vásárlásakor.</blockquote><p>Mindezek mellett az értékesítésben részt vevő szakemberek sem tudnak minden fontos kérdésre teljes választ adni.</p><h2>Ezért vagyunk mi, mert az AI nem tudja mindenre a választ.</h2><p>Nem vagyunk érdekeltek az értékesítésben. Azért vagyunk, hogy a döntésed előtt teljes képet kapj az ingatlanról.</p></div></section>
  <section className="section"><div className="site-container"><p className="display-kicker reveal">02 Mit csinálunk?</p><div className="verbs-grid"><div className="verb-list reveal">{["Megnézzük.","Feltárjuk.","Elmagyarázzuk.","Megtervezzük.","Kivitelezzük.","Végigkísérjük."].map((v,i)=><span className={i===5?"accent-text":""} style={{animationDelay:`${i*120}ms`}} key={v}>{v}</span>)}</div><div className="body-large reveal"><p>Nem állunk meg az állapotfelmérésnél. A vásárlás előtti vizsgálattól és a dokumentáció áttekintésétől a felújítás megtervezésén, megvalósításán és koordinációján át egészen az értékesítésig tudunk melletted lenni.</p><p>Ha befektetési céllal vásárolsz, abban is segítünk, hogy az ingatlanban rejlő lehetőségeket felismerd és ki tudd használni. Egy szakmai partner az első megtekintéstől a következő nagy döntésig.</p></div></div></div></section>
  <section className="section surface"><div className="site-container"><SectionHeading kicker="03 A folyamat" title="Így dolgozunk együtt."/><div className="process"><div className="step-rail">{steps.map((s,i)=><button key={s.rail} onClick={()=>chooseStep(i)} className={step===i?"active":""}><span>{String(i+1).padStart(2,"0")}</span>{s.rail}</button>)}</div><article className="stage-card" key={step} style={{backgroundImage:`linear-gradient(90deg, color-mix(in oklab, var(--deep) 96%, transparent) 0%, color-mix(in oklab, var(--deep) 76%, transparent) 60%, color-mix(in oklab, var(--deep) 38%, transparent)),url(${images.steps[step]})`}}><div className="stage-copy"><p className="kicker">{String(step+1).padStart(2,"0")} · {steps[step].kicker}</p><h3>{steps[step].title}</h3><p>{steps[step].body}</p><strong>{steps[step].label}</strong><ul>{steps[step].list.map(x=><li key={x}>{x}</li>)}</ul><em>{steps[step].note}</em>{steps[step].price&&<div className="stage-price">{steps[step].price}</div>}{steps[step].price&&<Link className="button-secondary" to="/szolgaltatasok">Árak és csomagok →</Link>}</div></article></div></div></section>
  <section className="section"><div className="site-container"><SectionHeading kicker="04 Szolgáltatások" title="Attól függően, hol tartasz."/><div className="segmented">{servicePanels.map((s,i)=><button key={s.tab} onClick={()=>setService(i)} className={service===i?"active":""}>{s.tab}</button>)}</div><article className="service-panel reveal"><div><p className="kicker">{servicePanels[service].tab}</p><h3>{servicePanels[service].title}</h3><Link className="button-primary" to="/kapcsolat">{servicePanels[service].cta}</Link></div><ul>{servicePanels[service].items.map(x=><li key={x}>{x}</li>)}</ul></article></div></section>
  <section className="section surface"><div className="site-container"><SectionHeading kicker="05 Értéknövelés" title="Nem minden felújítás teremt értéket." lead="Ha az ingatlan értékesítése a cél, segítünk megtalálni azokat a beavatkozásokat, amelyeknek műszaki és üzleti szempontból is van értelmük."/><p className="emphasis reveal">Nem az a cél, hogy mindent felújítsunk. Hanem hogy a megfelelő dolgokra költsünk.</p><div className="ba-carousel reveal"><div className="ba-label">Előtte / utána</div><img src={images.beforeAfter[slide]} alt={`Felújítás előtti és utáni állapot, ${slide+1}. példa`}/><span className="before-chip">Előtte</span><span className="after-chip">Utána</span><button className="carousel-arrow left" onClick={()=>moveSlide(-1)} aria-label="Előző kép"><ArrowLeft/></button><button className="carousel-arrow right" onClick={()=>moveSlide(1)} aria-label="Következő kép"><ArrowRight/></button></div><div className="dots">{images.beforeAfter.map((_,i)=><button key={i} className={slide===i?"active":""} onClick={()=>{setSlide(i);setManualSlide(true)}} aria-label={`${i+1}. kép`}/>)}</div></div></section>
  <section className="section independence"><div className="site-container"><SectionHeading kicker="06 · Függetlenség" title="Nem az a célunk, hogy megvedd. Nem az, hogy eladd." lead="Megmutatjuk a kockázatokat, a lehetőségeket és a várható következményeket."/><h3 className="statement reveal">Az a célunk, hogy jó döntést hozz.</h3><p className="body-large reveal">Te döntesz. Mi segítünk, hogy legyen mire alapoznod.</p><div className="stats">{[["30+","év tapasztalat"],["0","érdekeltség az ügyletben"],["100%","támogatás a döntésig"]].map(x=><div className="reveal" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></div></section>
  <section className="cta-section" style={{backgroundImage:`linear-gradient(90deg, color-mix(in oklab, var(--deep) 88%, transparent), color-mix(in oklab, var(--deep) 42%, transparent)),url(${images.cta})`}}><div className="site-container reveal"><h2>Mielőtt döntesz, nézzük meg együtt.</h2><p>Vásárlás Felújítás Értékesítés Bérlés</p><Link className="button-primary" to="/kapcsolat">Beszéljünk az ingatlanodról →</Link></div></section>
 </>;
}
