import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, ChevronLeft, ChevronRight } from "lucide-react";
import { images } from "@/assets/redesign";
import { SectionHeading } from "@/components/site/SiteLayout";

const problems = [
  ["Ingatlan jogi státusza", "Egy ingatlan lehet önálló ingatlan, telek, ház, ipari létesítmény vagy társasházi lakás. Mind másfajta jogi megközelítést igényel. A státusz felmérése elengedhetetlen a vásárlás előtt."],
  ["Műszaki állapot", "Az ingatlan általános műszaki állapota és a beépített anyagok, rendszerek élettartama."],
  ["Szerkezeti állapot", "Falak, födémek, statika, repedések, utólagos átalakítások nyoma."],
  ["Gépészet és műszaki rendszerek", "Fűtés, víz, szellőzés, elektromos hálózat: állapot, kapacitás, cserekötelezettség."],
  ["Tervrajzok és műszaki dokumentáció", "Ami a papíron van, és ami a valóságban: a kettő közti eltérés a kockázat."],
  ["Látható és rejtett hibák", "Amit friss festés vagy burkolat fed el, és amire érdemes külön figyelni."],
  ["Környezeti és használhatósági szempontok", "Tájolás, zaj, közös részek, megközelítés."],
  ["Felújítási és fenntartási költségek", "Átalakíthatóság, mi kerül pénzbe most, mi két éven belül, és mi lehet visszatérő költség."],
  ["Értékesítési szempontok vizsgálata", "Továbbértékesítésre szánt ingatlannál mekkora beruházást célszerű ráfordítani, hogy utána is versenyképes maradjon a piacon."],
];

const steps = [
 {rail:"Első megtekintés", kicker:"Első lépés", title:"Nézzük meg együtt az ingatlant.", body:"Segítünk akár már az első megtekintés során, még mielőtt bármi konkretizálódna benned az ingatlannal kapcsolatban.", label:"Amivel támogatunk", list:["a neked tetsző hirdetésekből segítünk szűkíteni azokra, amelyeket érdemes megtekinteni","a megtekintés során az ingatlanra vonatkozó szakmai kérdésekkel támogatunk","tudjuk, milyen dokumentumokra van szükség a szerződés aláírása előtt","segítünk eldönteni, érdemes-e egyáltalán továbblépni"],note:"Több ingatlan megtekintése esetén egyedi ajánlatot adunk.",price:"Első megtekintés · Lakás 50 000 Ft‑tól / Ház 70 000 Ft‑tól"},
 {rail:"Helyszíni felmérés", kicker:"Ha továbbléptünk", title:"Együtt nézzük meg a helyszínen.", body:"Ideálisan ekkorra már rendelkezésünkre áll az ingatlan dokumentációja, tervrajzai, a kapcsolódó műszaki anyagok és a jogi dokumentumok. A helyszínen ezeket összevetjük a valós állapottal.",label:"Amit a felmérésen teszünk",list:["műszaki és szerkezeti állapotvizsgálat","gépészeti rendszerek áttekintése","dokumentáció és valóság összevetése","figyelemfelhívás az esetleges hibalehetőségekre"],note:"Amit látunk, dokumentáljuk. Amit nem látunk, annak utánanézünk.",price:"Helyszíni felmérés · Lakás 150 000 Ft‑tól / Ház 200 000 Ft‑tól"},
 {rail:"Szakmai értékelés",kicker:"Tervezőasztal",title:"Leülünk a tervezőasztalhoz, és végigbeszéljük.",body:"A helyszíni tapasztalatokat és a dokumentációt együtt értékeljük, nyugodtan, az ingatlanon kívül.",label:"Amit végigveszünk",list:["mi a probléma","mekkora a kockázat","milyen megoldások vannak","milyen költségekkel számolj","mit érdemes most megtenni","milyen döntési lehetőségeid vannak"],note:"Segítünk átlátni, mit jelent mindez a te döntésed szempontjából.",price:"Szakmai értékelés és tervezés · Lakás 350 000 Ft‑tól / Ház 550 000 Ft‑tól"},
 {rail:"Tervezés",kicker:"Ha megveszed",title:"Megtervezzük, hogyan tovább.",body:"Ha az ingatlan megfelel az elképzeléseidnek, meghatározzuk a szükséges munkákat és prioritásokat, felmérjük a várható költségeket, és összeállítjuk a felújítás menetét.",label:"Amit összeállítunk",list:["szükséges munkák és prioritások","várható költségek reális sávokkal","műszaki megoldási javaslatok","a felújítás menete és ütemezése"],note:"Ha nem veszed meg, segítünk a keretedhez és az igényeidhez megfelelő ingatlant keresni.",price:"Szakmai értékelés és tervezés · Lakás 350 000 Ft‑tól / Ház 550 000 Ft‑tól"},
 {rail:"Megvalósítás",kicker:"Kivitelezés",title:"A tervekből megvalósítás lesz.",body:"Segítünk megfelelő kivitelezőt találni a teljes munkára vagy akár egyes szakágakra. A kivitelezés során koordináljuk a szakágakat, szükség esetén műszaki ellenőrzéssel támogatjuk a munkát, és végigkísérjük a folyamatot az átadásig.",label:"Amit kézben tartunk",list:["kivitelező kiválasztása teljes munkára vagy szakáganként","tervezés","kivitelezés","koordináció","műszaki ellenőrzés","átadás"],note:"Te pedig végig tudod, mi történik, miért történik, és mibe kerül.",price:"Projektmenedzsment · Lakás 1 200 000 Ft‑tól / Ház egyedi ajánlat"},
 {rail:"Az eredmény",kicker:"Döntési pozíció",title:"Egy saját ingatlan, amivel már tudod, mit lehet kezdeni.",body:"Legyen szó saját otthonról, befektetésről vagy későbbi értékesítésről, a cél, hogy az ingatlanban rejlő lehetőségeket és korlátokat ismerve hozd meg a döntéseidet.",label:"Ahol ez számít",list:["saját otthon","befektetés és hozam","későbbi értékesítés","bérbeadás"],note:"Ha a későbbi értékesítés a cél, abban is segítünk, hogy a beruházásod célirányos legyen, felmérve a későbbi értékesítési lehetőségeket és a piacot. Természetesen az értékesítés folyamatában is tudunk segíteni."}
];

const servicePanels = [
 {tab:"Vevői oldal",title:"Mielőtt megveszed.",cta:"Vásárlás előtt →",items:["Vásárlás előtti műszaki felmérés","Ingatlankockázat-felmérés","Dokumentáció és tervrajzok áttekintése","Várható felújítási költségek felmérése","Befektetési célú ingatlan szakmai értékelése","Döntéstámogatás"]},
 {tab:"Eladói oldal",title:"Mielőtt piacra lépsz.",cta:"Eladás előtt →",items:["Eladás előtti műszaki állapotfelmérés","Problémák és kockázatok feltárása","Felújítási és értéknövelési javaslatok","Felújítás koordinációja","Értékesítés előtti felkészítés","Értékesítési támogatás"]},
 {tab:"Bérlői oldal",title:"Mielőtt aláírod.",cta:"Bérlés előtt →",items:["Bérlés előtti állapotfelmérés","Műszaki problémák feltárása","Használhatósági szempontok vizsgálata","Dokumentáció áttekintése","Döntéstámogatás"]},
 {tab:"Bérbeadói oldal",title:"Mielőtt bérbe adod.",cta:"Bérbeadás előtt →",items:["Bérlő kiválasztása és ellenőrzése","Bérleti szerződés ellenőrzése","Kaució és fizetési feltételek ellenőrzése","Átadás-átvétel dokumentálása","Közüzemi elszámolások ellenőrzése","Karbantartási és kárrendezési ügyek kezelése"]}
];

export default function Home() {
 const [problem,setProblem]=useState(0); const [step,setStep]=useState(0); const [manualStep,setManualStep]=useState(false); const [service,setService]=useState(0); const [slide,setSlide]=useState(0); const [manualSlide,setManualSlide]=useState(false);
 const railRef=useRef<HTMLDivElement>(null); const [railEdges,setRailEdges]=useState({left:false,right:true});
 useEffect(()=>{if(manualStep)return;const id=window.setInterval(()=>setStep(v=>(v+1)%steps.length),6400);return()=>clearInterval(id)},[manualStep]);
 useEffect(()=>{if(manualSlide)return;const id=window.setInterval(()=>setSlide(v=>(v+1)%images.beforeAfter.length),5200);return()=>clearInterval(id)},[manualSlide]);
 const measureRail=()=>{const el=railRef.current;if(!el)return;const max=el.scrollWidth-el.clientWidth;setRailEdges({left:el.scrollLeft>1,right:el.scrollLeft<max-1})};
 useEffect(()=>{measureRail();const el=railRef.current;if(!el)return;const on=()=>measureRail();el.addEventListener("scroll",on,{passive:true});window.addEventListener("resize",on);return()=>{el.removeEventListener("scroll",on);window.removeEventListener("resize",on)}},[]);
 useEffect(()=>{const el=railRef.current;if(!el)return;if(el.scrollWidth-el.clientWidth<=1)return;const b=el.children[step] as HTMLElement|undefined;if(!b)return;const target=Math.max(0,Math.min(b.offsetLeft-(el.clientWidth-b.offsetWidth)/2,el.scrollWidth-el.clientWidth));el.scrollTo({left:target,behavior:"smooth"})},[step]);
 const chooseStep=(i:number)=>{setStep(i);setManualStep(true)}; const stepBy=(d:number)=>chooseStep(Math.min(steps.length-1,Math.max(0,step+d))); const moveSlide=(n:number)=>{setSlide((slide+n+4)%4);setManualSlide(true)};
 return <div className="home-page">
  <section className="hero hx-slide" style={{["--hero-image" as string]:`url(${images.hero})`}}><div className="site-container hero-content"><p className="hero-kicker">ingatlankockázat.hu</p><h1 className="hx-hero-title"><span className="hx-light">Egy ingatlan lehet gyönyörű, és tűnhet jó befektetésnek.</span><span className="hx-strong">Azonban az első benyomás után érhetnek meglepetések.</span></h1><p className="hero-lead">Szembejöhetnek olyan problémák, amiket elsőre nem veszel észre.</p><Link to="/kapcsolat" className="button-primary">Felülvizsgáltatom az ingatlant →</Link></div></section>
  <section className="hx-slide hx-before"><div className="site-container hx-two hx-divided reveal"><div><p className="hx-eyebrow">Mielőtt döntesz</p><p className="hx-big">Nézzük meg, milyen állapotban van valójában, milyen kockázatokkal és költségekkel számolj, és <span className="accent-text">milyen lehetőségek vannak benne.</span></p></div><div className="hx-divider-col"><p className="hx-lead">Független műszaki és szakmai támogatás vásárlás, felújítás és értékesítés előtt, közben és után.</p><div className="pill-row">{["Vásárlás","Felújítás","Értékesítés","Bérlés"].map(x=><span className="outline-pill" key={x}>{x}</span>)}</div></div></div></section>
  <section className="hx-slide hx-problem" style={{["--hx-img" as string]:`url(${images.quote})`}}><div className="site-container hx-problem-inner"><div className="hx-problem-copy"><p className="hx-num-eyebrow reveal"><b>01</b> A probléma</p><h2 className="hx-upper reveal">Amit elsőre látsz, az nem feltétlenül a teljes kép.</h2><p className="hx-body reveal">A laikus szem sokszor nem veszi észre egy ingatlan valódi kockázatait. Lehetnek műszaki és jogi problémák, amelyek azonnal vagy csak később okoznak komoly költséget. És lehetnek olyanok is, amelyekről azt sem tudod, hogy meg kellene vizsgálnod.</p><p className="hx-sub-eyebrow reveal">Mi segítünk feltárni</p><div className="hx-acc reveal">{problems.map((p,i)=><div className={`hx-acc-item ${problem===i?"active":""}`} key={p[0]}><button onClick={()=>setProblem(problem===i?-1:i)} aria-expanded={problem===i}><span>{p[0]}</span><b>{problem===i?"−":"+"}</b></button>{problem===i&&<p>{p[1]}</p>}</div>)}</div><p className="hx-closing reveal">A cél, hogy az összes fontos kérdésre még a döntés előtt megfelelő válasz legyen.</p></div></div></section>
  <section className="hx-slide hx-quote"><div className="site-container hx-quote-inner reveal"><span className="hx-qmark">”</span><div><blockquote>A mai magyar ingatlanpiacon egy laikus első nekifutásra <span className="accent-text">kevesebb információval rendelkezik, mint egy használt autó vásárlásakor.</span></blockquote><p className="hx-lead">Mindezek mellett az értékesítésben részt vevő szakemberek sem tudnak minden fontos kérdésre teljes választ adni.</p><hr/><h3 className="hx-upper accent-text">Ezért vagyunk mi, mert az AI nem tudja mindenre a választ.</h3><p className="hx-lead">Nem vagyunk érdekeltek az értékesítésben. Azért vagyunk, hogy a döntésed előtt teljes képet kapj az ingatlanról.</p></div></div></section>
  <section className="hx-slide surface hx-what"><div className="site-container"><p className="hx-num-eyebrow reveal"><b>02</b> Mit csinálunk?</p><p className="hx-verbs reveal">{["Megnézzük.","Feltárjuk.","Elmagyarázzuk.","Megtervezzük.","Kivitelezzük.","Végigkísérjük."].map((v,i)=><span className={i===5?"accent-text":""} key={v}>{v} </span>)}</p><div className="hx-two hx-lead reveal"><p>Nem állunk meg az állapotfelmérésnél. A vásárlás előtti vizsgálattól és a dokumentáció áttekintésétől a felújítás megtervezésén, megvalósításán és koordinációján át egészen az értékesítésig tudunk melletted lenni.</p><p>Ha befektetési céllal vásárolsz, abban is segítünk, hogy az ingatlanban rejlő lehetőségeket felismerd és ki tudd használni. <span className="accent-text">Egy szakmai partner az első megtekintéstől a következő nagy döntésig.</span></p></div></div></section>
  <section className="hx-slide hx-flow"><div className="site-container"><p className="hx-num-eyebrow"><b>03</b> A folyamat</p><h2 className="hx-upper">Így dolgozunk együtt.</h2><div className="hx-process"><div className="hx-rail-wrap"><div className="hx-rail" ref={railRef}>{steps.map((s,i)=><button key={s.rail} onClick={()=>chooseStep(i)} className={step===i?"active":""}><span>{String(i+1).padStart(2,"0")}</span>{i===0?"Első lépés":s.rail}</button>)}</div><span className="hx-rail-fade hx-rail-fade-l" data-show={railEdges.left} aria-hidden="true"/><span className="hx-rail-fade hx-rail-fade-r" data-show={railEdges.right} aria-hidden="true"/></div><div className="hx-rail-nav"><button type="button" className="hx-rail-arrow hx-rail-arrow-l" onClick={()=>stepBy(-1)} disabled={!railEdges.left} aria-label="Előző folyamatlépés"><ChevronLeft/></button><p className="hx-rail-hint">Húzd oldalra a többi lépésért</p><button type="button" className="hx-rail-arrow hx-rail-arrow-r" onClick={()=>stepBy(1)} disabled={!railEdges.right} aria-label="Következő folyamatlépés"><ChevronRight/></button></div><article className="hx-stage" key={step}><div className="hx-stage-copy"><p className="hx-small-eyebrow">{String(step+1).padStart(2,"0")} · {steps[step].kicker}</p><h3 className="hx-upper">{steps[step].title}</h3><p className="hx-body">{steps[step].body}</p><p className="hx-tiny">{steps[step].label}</p><ul>{steps[step].list.map(x=><li key={x}>{x}</li>)}</ul>{steps[step].price&&<div className="stage-price">{steps[step].price}</div>}<em>{steps[step].note}</em></div><div className="hx-stage-img"><img src={images.steps[step]} alt={steps[step].rail}/></div></article></div></div></section>
  <section className="hx-slide surface hx-svc"><div className="site-container"><div className="hx-head-row"><div><p className="hx-num-eyebrow"><b>04</b> Szolgáltatások</p><h2 className="hx-upper">Attól függően, hol tartasz.</h2></div><div className="hx-seg">{servicePanels.map((s,i)=><button key={s.tab} onClick={()=>setService(i)} className={service===i?"active":""}>{s.tab}</button>)}</div></div><article className="hx-panel"><div className="hx-panel-left"><p className="hx-small-eyebrow">{servicePanels[service].tab}</p><h3 className="hx-upper">{servicePanels[service].title}</h3><Link className="button-primary" to="/kapcsolat">{servicePanels[service].cta}</Link></div><ul>{servicePanels[service].items.map(x=><li key={x}>{x}</li>)}</ul></article></div></section>
  <section className="hx-slide"><div className="site-container"><p className="hx-num-eyebrow"><b>05</b> Értéknövelés</p><div className="hx-two hx-value"><div className="reveal"><h2 className="hx-upper">Nem minden felújítás teremt értéket.</h2><p className="hx-body">Ha az ingatlan értékesítése a cél, segítünk megtalálni azokat a beavatkozásokat, amelyeknek műszaki és üzleti szempontból is van értelmük.</p><p className="hx-emph">Nem az a cél, hogy mindent felújítsunk. <span className="accent-text">Hanem hogy a megfelelő dolgokra költsünk.</span></p></div><div><div className="hx-ba-top"><span className="hx-tiny">Előtte / utána</span><div className="hx-dashes">{images.beforeAfter.map((_,i)=><button key={i} className={slide===i?"active":""} onClick={()=>{setSlide(i);setManualSlide(true)}} aria-label={`${i+1}. kép`}/>)}</div></div><div className="ba-carousel hx-ba"><img src={images.beforeAfter[slide]} alt={`Felújítás előtti és utáni állapot, ${slide+1}. példa`}/><span className="hx-chip hx-chip-l">Előtte</span><span className="hx-chip hx-chip-r">Utána</span><button className="carousel-arrow left" onClick={()=>moveSlide(-1)} aria-label="Előző kép"><ArrowLeft/></button><button className="carousel-arrow right" onClick={()=>moveSlide(1)} aria-label="Következő kép"><ArrowRight/></button></div></div></div></div></section>
  <section className="hx-indep"><div className="hx-indep-l"><p className="hx-num-eyebrow">06 · Függetlenség</p><h2 className="hx-upper">Nem az a célunk, hogy megvedd. Nem az, hogy eladd.</h2><p className="hx-lead">Megmutatjuk a kockázatokat, a lehetőségeket és a várható következményeket.</p></div><div className="hx-indep-r"><h2 className="hx-upper accent-text">Az a célunk, hogy jó döntést hozz.</h2><p className="hx-emph">Te döntesz. Mi segítünk, hogy legyen mire alapoznod.</p><div className="hx-stats">{[["30+","év tapasztalat"],["0","érdekeltség az ügyletben"],["100%","támogatás a döntésig"]].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></div></section>
  <section className="hx-cta"><div className="hx-cta-bar"/><div className="hx-cta-body" style={{["--hx-img" as string]:`url(${images.cta})`}}><div className="site-container"><div className="hx-cta-copy reveal"><h2 className="hx-upper">Mielőtt döntesz, nézzük meg együtt.</h2><p className="hx-words">{["Vásárlás","Felújítás","Értékesítés","Bérlés"].map(w=><span key={w}>{w}</span>)}</p><Link className="button-light" to="/kapcsolat">Beszéljünk az ingatlanodról →</Link></div></div></div></section>
  </div>;
}
