import { useState } from "react";
import { Link } from "react-router-dom";

const packages = [
 {name:"Első konzultáció",flat:"Díjmentes",unit:"telefonon",cta:"Beszéljünk",desc:"Kb. 30 perces telefonos beszélgetés arról, mit szeretnél az ingatlannal kezdeni. Ebben még nem adunk szakmai tanácsot, hanem tájékoztatunk arról, milyen formában tudunk együttműködni."},
 {name:"Első megtekintés",home:"50 000 Ft‑tól",house:"70 000 Ft‑tól",cta:"Megtekintést kérek",desc:"Veled tartunk a megtekintésre, szakmai kérdésekkel támogatunk, és segítünk eldönteni, érdemes-e továbblépni. Több ingatlan megtekintése esetén egyedi ajánlat.",items:["a neked tetsző hirdetésekből segítünk szűkíteni azokra, amelyeket érdemes megtekinteni","a megtekintés során az ingatlanra vonatkozó szakmai kérdésekkel támogatunk","tudjuk, milyen dokumentumokra van szükség a szerződés aláírása előtt","segítünk eldönteni, érdemes-e egyáltalán továbblépni"]},
 {name:"Helyszíni felmérés",home:"150 000 Ft‑tól",house:"200 000 Ft‑tól",cta:"Felmérést kérek",desc:"A dokumentáció birtokában szakvélemény a helyszínen: a valós állapot összevetése a papírokkal és a hibalehetőségek feltárása.",items:["műszaki és szerkezeti állapotvizsgálat","gépészeti rendszerek áttekintése","dokumentáció és valóság összevetése","figyelemfelhívás az esetleges hibalehetőségekre"]},
 {name:"Szakmai értékelés és tervezés",home:"350 000 Ft‑tól",house:"550 000 Ft‑tól",cta:"Érdekel",desc:"Felújítási és korszerűsítési tanácsadás: reális kép a szükséges munkákról, a várható költségekről, a lehetséges műszaki megoldásokról és a megvalósítás sorrendjéről.",items:["mi a probléma és mekkora a kockázat","milyen megoldások vannak","milyen költségekkel számolj, reális sávokkal","mit érdemes most megtenni","milyen döntési lehetőségeid vannak","szükséges munkák és prioritások","műszaki megoldási javaslatok","a felújítás menete és ütemezése"]},
 {name:"Projektmenedzsment",home:"1 200 000 Ft‑tól",house:"Egyedi ajánlat",cta:"Projektet indítok",desc:"A teljes beruházás szakmai koordinációja az első egyeztetéstől egészen az átadásig.",items:["kivitelező kiválasztása teljes munkára vagy szakáganként","ajánlatok szakmai összehasonlítása","tervezés","kivitelezés és a szakágak koordinációja","műszaki ellenőrzések, helyszíni bejárások","folyamatos szakmai képviselet","átadás"]},
 {name:"Konfliktuskezelés, vitarendezés",flat:"39 000 Ft",unit:"/ óra",cta:"Időpontot kérek",desc:"Közvetítői, tárgyalói támogatás ingatlannal kapcsolatos feszült vagy vitás helyzetekben.",items:["tisztázó beszélgetés lebonyolítása","félreértések, ellentétek rendezése","vitás helyzetek szakmai közvetítése","megállapodás előkészítése","független szakmai álláspont kialakítása"]}
];
export default function ServicesPage(){const[house,setHouse]=useState(false);return <div className="page-shell services-page"><section className="page-hero site-container"><p className="display-kicker">Szolgáltatások és csomagok</p><h1>Az első konzultációtól a teljes projektmenedzsmentig.</h1><p className="lead">Független szakmai támogatás minden fontos ingatlandöntéshez.</p><div className="price-controls"><strong>Árak megjelenítése</strong><div className="segmented" aria-label="Ingatlantípus"><button type="button" className={!house?"active":""} onClick={()=>setHouse(false)}>Lakás</button><button type="button" className={house?"active":""} onClick={()=>setHouse(true)}>Családi ház</button></div></div></section><section className="site-container pb-section"><div className="package-grid">{packages.map((p,i)=><article className={`package-card reveal ${i===3?"package-card--featured":""}`} key={p.name}><div className="package-title"><span className="package-no">{String(i+1).padStart(2,"0")}</span><h2>{p.name}</h2></div><div className="package-price">{p.flat??(house?p.house:p.home)} {p.unit&&<small>{p.unit}</small>}</div><p>{p.desc}</p>{p.items&&<><strong className="list-label">Tartalma</strong><ul>{p.items.map(x=><li key={x}>{x}</li>)}</ul></>}<Link className="button-secondary" to="/kapcsolat">{p.cta} <span aria-hidden="true">→</span></Link></article>)}</div><div className="extras reveal"><h2>Kiegészítő szolgáltatások</h2><div>{["Teljes körű pénzügyi tanácsadás, hitel és biztosítás","Ingatlan jogi hátterének áttekintése","Adásvételi folyamat nyomon követése, szakmai felügyelete","Karbantartási és üzemeltetési tanácsadás"].map(x=><span key={x}><i aria-hidden="true" />{x}</span>)}</div></div></section></div>}
